# webrtc_gateway configuration

stt_service:
  # STT 서비스 gRPC 엔드포인트 (host:port)
  address: "stt-service:50052"

tts_service:
  # TTS 서비스 gRPC 엔드포인트 (host:port)
  address: "tts-service:50053"

server:
  # WebSocket(Signaling) 포트
  websocket_port: 8443
  # (선택) TLS 인증서 경로
  tls_cert_path: "/etc/webrtc_gateway/cert.pem"
  tls_key_path: "/etc/webrtc_gateway/key.pem"

metrics:
  # Prometheus 메트릭 노출 포트
  port: 9090

ice_servers:
  # STUN/TURN 서버 목록
  - urls:
      - "stun:stun.l.google.com:19302"
  - urls:
      - "turn:turn.example.com:3478"
    username: "turn_user"
    credential: "turn_pass"
