# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x06protos\"2\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"%\n\x15TranscriptionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2O\n\nASRService\x12\x41\n\nTranscribe\x12\x14.protos.AudioRequest\x1a\x1d.protos.TranscriptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOREQUEST']._serialized_start=21
  _globals['_AUDIOREQUEST']._serialized_end=71
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=73
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=110
  _globals['_ASRSERVICE']._serialized_start=112
  _globals['_ASRSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
