services:
  # 1. Mock LLM Engine Service (for testing)
  mock-llm:
    build:
      context: .
      # Dockerfile.external_test 사용 명시
      dockerfile: Dockerfile.external_test
      args:
        - TARGET_ARCH=${TARGET_ARCH}
    container_name: mock-llm-server
    # mock_llm_server.py 스크립트를 직접 실행하도록 수정
    command: ["python", "/app/tests/mock_llm_server.py"]
    ports:
      - "50051:50051" # Mock LLM 포트 (외부 접근이 필요 없다면 제거 가능)
    networks:
      - stt_test_net
    # Python 출력 버퍼링 비활성화 (로그 즉시 확인용)
    environment:
      - PYTHONUNBUFFERED=1

  # 2. STT Service (Main Application)
  stt-service:
    build:
      context: .
      dockerfile: Dockerfile # 메인 서비스용 Dockerfile
      args:
        - TARGET_ARCH=${TARGET_ARCH}
    container_name: stt-service
    env_file:
      - .env # .env 파일에서 환경 변수 로드
    environment:
      # Mock LLM 서비스 이름과 포트로 설정
      - LLM_ENGINE_ADDRESS=mock-llm:50051
      - STT_SERVER_ADDRESS=0.0.0.0:50056
    ports:
      - "50056:50056" # STT 서비스 gRPC 포트
    depends_on:
      - mock-llm # Mock LLM이 먼저 시작되도록 설정
    networks:
      - stt_test_net
    # Healthcheck 추가 고려 (mock-llm 준비 완료 후 stt-service 시작)
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"] # 예시 (grpc-health-probe 설치 필요)
      interval: 5s
      timeout: 3s
      retries: 5

  # 3. Test Client (Runs Python Integration Tests)
  test-client:
    build:
      context: .
      # Dockerfile.external_test 사용 명시
      dockerfile: Dockerfile.external_test
      args:
        - TARGET_ARCH=${TARGET_ARCH}
    container_name: test-stt-client
    environment:
      # 테스트 대상 STT 서비스 주소 설정
      - STT_SERVICE_ADDRESS=stt-service:50056
      # 오디오 파일 경로 수정 (Dockerfile 내부 경로)
      - AUDIO_SAMPLE_PATH=/app/sample.wav
      # Python 출력 버퍼링 비활성화
      - PYTHONUNBUFFERED=1
      # MOCK_LLM_SERVICE_ADDRESS는 테스트 코드에서 사용하지 않으므로 제거
    depends_on:
      # stt-service가 준비된 후 테스트 시작 (healthcheck 사용 권장)
      stt-service:
         condition: service_started # 또는 service_healthy (healthcheck 설정 시)
      # mock-llm은 stt-service가 의존하므로 명시적 의존성 불필요할 수 있음
      # mock-llm:
      #   condition: service_started
    networks:
      - stt_test_net
    # pytest 명령어를 명시적으로 실행하도록 수정
    command: ["pytest", "/app/tests/external_integration_test.py", "-v", "-s"]

networks:
  stt_test_net: